export const AppColors = {
  primary: '#2491ff',
  secondary: '#F59E0B',
  background: '#F9F7FD',
  surface: '#FFFFFF',
  textPrimary: '#374151',
  textSecondary: '#6B7280',
  success: '#10B981',
  error: '#EF4444',
  info: '#2491ff',
  divider: '#F3F4F6',

  primaryLight: '#59adff',
  primaryDark: '#0077e6',
  accent: '#EC4899',
  accentLight: '#F472B6',
  warning: '#F97316',
  tertiary: '#EF4444',

  backgroundDark: '#1F1B24',
  surfaceDark: '#2D1B3D',
  textPrimaryDark: '#F9FAFB',
  textSecondaryDark: '#D1D5DB',
} as const

export const Colors = {
  light: {
    text: AppColors.textPrimary,
    textSecondary: AppColors.textSecondary,
    background: AppColors.background,
    surface: AppColors.surface,
    primary: AppColors.primary,
    secondary: AppColors.secondary,
    success: AppColors.success,
    error: AppColors.error,
    info: AppColors.info,
    divider: AppColors.divider,
    tint: AppColors.primary,
    tabIconDefault: AppColors.textSecondary,
    tabIconSelected: AppColors.primary,
  },
  dark: {
    text: AppColors.textPrimaryDark,
    textSecondary: AppColors.textSecondaryDark,
    background: AppColors.backgroundDark,
    surface: AppColors.surfaceDark,
    primary: AppColors.primary,
    secondary: AppColors.secondary,
    success: AppColors.success,
    error: AppColors.error,
    info: AppColors.info,
    divider: AppColors.textSecondaryDark,
    tint: AppColors.primaryLight,
    tabIconDefault: AppColors.textSecondaryDark,
    tabIconSelected: AppColors.primaryLight,
  },
}
