app = 'unisync-server' 
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  API_VERSION = "v1"
  APP_VERSION = "1.0.0"
  LOG_LEVEL = "info"
  LOG_FILE_ENABLED = "true"
  JWT_ACCESS_TOKEN_EXPIRY = "1h"
  JWT_REFRESH_TOKEN_EXPIRY = "30d"
  RATE_LIMIT_WINDOW_MS = "900000"
  RATE_LIMIT_MAX_REQUESTS = "100"
  OTP_EXPIRY_MINUTES = "5"
  OTP_MAX_ATTEMPTS = "5"
  OTP_LENGTH = "6"
  OTP_BCRYPT_ROUNDS = "12"
  OTP_SEND_LIMIT_PER_HOUR = "3"
  OTP_SEND_LIMIT_PER_IP_PER_HOUR = "10"
  OTP_VERIFY_LIMIT_PER_15MIN = "5"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false # Set to true for dev to save costs
  auto_start_machines = true
  min_machines_running = 1 # Increase for production
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/api/v1/health"

[[vm]]
  memory = '512mb' 
  cpu_kind = 'shared'
  cpus = 1

