# fly.toml app configuration file generated for unisync-api on 2025-07-24T23:08:09+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'unisync-api'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 9201
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  NODE_ENV = "production"
  LOG_LEVEL = "info"
  LOG_FILE_ENABLED=true
  API_VERSION = "v1"
  APP_VERSION = "1.0.0"
  JWT_ACCESS_TOKEN_EXPIRY = "1h"
  JWT_REFRESH_TOKEN_EXPIRY = "30d"
  RATE_LIMIT_WINDOW_MS=900000
  RATE_LIMIT_MAX_REQUESTS=100




