-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "academic"."users" add column "is_email_verified" boolean
--  not null default 'false';
