import type { Metadata } from "next";
import { ApolloProvider } from "@/providers/Apollo";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body>
        <ApolloProvider>{children}</ApolloProvider>
      </body>
    </html>
  );
};
export default RootLayout;
