import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { ApolloProvider } from "@/providers/Apollo";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body>
        <AntdRegistry>
          <ApolloProvider>{children}</ApolloProvider>
        </AntdRegistry>
      </body>
    </html>
  );
};
export default RootLayout;
