version: 3
endpoint:
  from_env: HASURA_GRAPHQL_ENDPOINT
metadata_directory: metadata
admin_secret:
  from_env: HASURA_GRAPHQL_ADMIN_SECRET
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
